import verticalRhythm from 'compass-vertical-rhythm';
import ms from 'modularscale';

// Copied from Typography.js: Styled Components should have the same font sizes
// and line heights as styles generated by Typography.js
const createVerticalRhythm = ({ baseFontSize, scaleRatio }) => {
	const vr = verticalRhythm({
		baseFontSize,
	});
	vr.scale = value => {
		const baseFont = parseInt(baseFontSize, 10);
		const newFontSize = `${ms(value, scaleRatio) * baseFont}px`;
		return vr.adjustFontSizeTo(newFontSize);
	};
	return vr;
};

export default createVerticalRhythm;
