import {
	createElement,
	useMemo,
	type ElementType,
	type RefObject,
} from 'react';
import { type HTMLStyledProps } from '../../styled-system/jsx';
import {
	splitProps,
	normalizeHTMLProps,
} from '../../styled-system/helpers.mjs';
import { isCssProperty } from '../../styled-system/jsx/is-valid-prop.mjs';
import { css as cssFn, cx } from '../../styled-system/css';

// React components generated by Panda doesn't have `as` prop
// This is exact copy of Panda's Box component but with the `as` prop

export type AsProp<C extends ElementType> = {
	/** HTML element to render the box */
	as?: C;
};

export type RefProp<C extends ElementType> = {
	/** Ref to pass to the underlying HTML element */
	innerRef?: RefObject<C>;
};

export type BoxProps<C extends ElementType> = HTMLStyledProps<C> &
	AsProp<C> &
	RefProp<C>;

/**
 * Generic styled component factory.
 *
 * function Box({as, ...props}) {
 *   return createBox(as ?? 'div', props);
 * }
 */
export function createBox(
	// We don't use BoxProps here to suppress the "Expression produces
	// a union type that is too complex to represent" error
	{ as, innerRef, className, css, ...props }: Record<string, any>,
	/** Default HTML element */
	defaultElement: ElementType = 'div'
) {
	const [htmlProps, styleProps, elementProps] = useMemo(() => {
		return splitProps(props, normalizeHTMLProps.keys, isCssProperty);
	}, [props]);

	return createElement(as ?? defaultElement, {
		ref: innerRef,
		...elementProps,
		...normalizeHTMLProps(htmlProps),
		className: cx(cssFn(styleProps, css), className),
	});
}

/**
 * Generic container with responsive props to control whitespace, layout,
 * positioning and colors.
 */
export function Box<C extends ElementType>(props: BoxProps<C>) {
	return createBox(props);
}
